toevoegen radius folder en scherpstellen gbif codes
inbo/prius-radius pull request #36
Opened 2023-11-07 12:55 UTC by fleurpet

In deze branch: 
1. opsplitsing prius en radius folder; README, .gitignore, R project etc. toegevoegd aan radius folder
2. in script preparing_radius_species_list.Rmd: vergelijking prius gbif codes met de unielijst (Adriaens & Oldoni, 2023) en valideren codes tov GBIF Backbone Taxonomy

@SanderDevisscher enkele moeilijkheden: 
- deze branch is foutief gelinkt aan issue #35, kan dit nog gewijzigd worden zodat deze issue niet wordt gesloten wanneer deze branch met de main wordt gemerged? 
- ondanks dat ik .Rproj.user heb toegevoegd aan de .gitignore, staat deze nog steeds in de repository. Hoe kan ik deze verwijderen?

2023-11-07 13:54 UTC, SanderDevisscher requested changes
@fleurpet bestanden zoals .gitignore en license<sup>1</sup> zijn eigen aan een repository en horen thuis in de root<sup>2</sup> van de repo. Het feit dat je dergelijk bestand op meerdere niveaus hebt staan veroorzaakt conflicten 

<sup>1</sup> maar ook o.a. het .Rproj-bestand en de bijhorende bestanden horen enkel in de root te staan. Net zoals bestanden die omgaan met credentials (bvb .renviron) en speciale settings voor je rstudio (zoals .rprofile).

<sup>2</sup> De eerste folder waar je in terechtkomt zonder door te klikken. 

Plaats je de bestanden terug in de root AUB ? Hierna zal ik de review in earnest verderzetten.

2023-11-07 14:15 UTC, fleurpet commented
@SanderDevisscher de genoemde files (.Rproject, license, .gitignore, ...) staan opnieuw in de root van de repository.

2023-11-07 14:42 UTC, SanderDevisscher requested changes
@fleurpet ik heb de "hangende" rproj.user files uit de PR verwijderd (zie 3f0ee31b9550781effe832060bb659fdc92e2577).

Als jij nu nog de laatste aanpassingen doet, vooral het duplicaat van prius_species_list verwijderen, kan ik de PR goedkeuren.

2023-11-07 14:42 UTC, SanderDevisscher commented on radius/data/input/prius_species_list.csv
@fleurpet ik ben geen fan van dubbele files. Je kan naar de file in de prius map verwijzen door "./prius/data/input/prius_species_list.csv" te gebruiken. 

Check hiervoor wel of je de volgende settings juist staan:
Tools > Global Options > R Markdown > Evaluate chuncks in directory == "project"

2023-11-07 14:42 UTC, SanderDevisscher commented on radius/r-scripts/preparing_radius_species_list.Rmd
> +library(readr)
maakt deel uit van tidyverse, 1 of het ander

2023-11-08 07:12 UTC, fleurpet commented
@SanderDevisscher  Ik heb de laatste aanpassingen doorgevoerd. Bedankt voor de hulp!

2023-11-08 08:21 UTC, SanderDevisscher approved these changes

2023-11-08 08:22 UTC, SanderDevisscher approved these changes
Zo ziet het er goed uit.

2023-11-08 08:22 UTC, merged